POST http://localhost:3000/login/
Content-Type: application/json

{
    "username": "svn",
    "password": "123456"
}


###
POST http://localhost:3000/routes/search
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWI0ZjBkMzc5MjZiMDg2Y2Q1YjFiNSIsInVzZXJuYW1lIjoic3ZuIiwiaWF0IjoxNjg0OTM0NDQxLCJleHAiOjE2ODUwMjA4NDF9.gCGoyWJXR65aL8uhtSuMsu1xEjiHDAK3rT_u9YzktS8

{
  "start": "64699f8fa39bcf193c8be630",
  "end": "64699f8fa39bcf193c8be632"
}

###
GET http://localhost:3000/tickets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWI0ZjBkMzc5MjZiMDg2Y2Q1YjFiNSIsInVzZXJuYW1lIjoic3ZuIiwiaWF0IjoxNjg1MDAzMzA1LCJleHAiOjE2ODUwODk3MDV9.cEPC0z9psbrdk0iLoIVoTqxpvCHpy6XtnLGb95qDriQ

###
POST http://localhost:3000/tickets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWI0ZjBkMzc5MjZiMDg2Y2Q1YjFiNSIsInVzZXJuYW1lIjoic3ZuIiwiaWF0IjoxNjg1MDAzMzA1LCJleHAiOjE2ODUwODk3MDV9.cEPC0z9psbrdk0iLoIVoTqxpvCHpy6XtnLGb95qDriQ
Content-Type: application/json

{
  "routeId": "6461a31986ad133c1067312a",
  "startStop": "64699f8fa39bcf193c8be631",
  "endStop": "64699f8fa39bcf193c8be635",
  "price": 10000,
  "userId": "645b4f0d37926b086cd5b1b5"
}

###
POST http://localhost:3000/tickets/getTicketsByUserId
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWI0ZjBkMzc5MjZiMDg2Y2Q1YjFiNSIsInVzZXJuYW1lIjoic3ZuIiwiaWF0IjoxNjg1MDAzMzA1LCJleHAiOjE2ODUwODk3MDV9.cEPC0z9psbrdk0iLoIVoTqxpvCHpy6XtnLGb95qDriQ
Content-Type: application/json

{
  "userId": "645b4f0d37926b086cd5b1b5"
}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "username": "anhsengdeptrai",
    "password": "123456",
    "fullName": "Sang Vinh Nguyen"
}


###

GET http://localhost:3000/routes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWI0ZjBkMzc5MjZiMDg2Y2Q1YjFiNSIsInVzZXJuYW1lIjoic3ZuIiwiaWF0IjoxNjg0OTA3MDM2LCJleHAiOjE2ODQ5OTM0MzZ9.IFVk7zHtXZDcQVdlOFoxxwjCP2L1GGyRF8dnqmI29Fc

###
GET http://localhost:3000/routes/6461a31986ad133c1067312a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWI0ZjBkMzc5MjZiMDg2Y2Q1YjFiNSIsInVzZXJuYW1lIjoic3ZuIiwiaWF0IjoxNjg0OTA3MDM2LCJleHAiOjE2ODQ5OTM0MzZ9.IFVk7zHtXZDcQVdlOFoxxwjCP2L1GGyRF8dnqmI29Fc

###
GET http://localhost:3000/busStops/64699f8fa39bcf19ca8be636
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWI0ZjBkMzc5MjZiMDg2Y2Q1YjFiNSIsInVzZXJuYW1lIjoic3ZuIiwiaWF0IjoxNjg0OTM1MDQ5LCJleHAiOjE2ODUwMjE0NDl9.bHiRO4maypzkZVPQnkjd9XOLew8IkBvHfbS9te_7_GQ



POST http://localhost:3000/token/
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ1c2VyIiwiaWF0IjoxNjgzNzA0NjkxLCJleHAiOjE2ODQzMDk0OTF9.BcazgdB2d1ZHihY3kDDiRCkYHooXDW3GwiulOvYvpLw"
}

###

GET http://localhost:3000/busStops/search/Đại%20Học
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWI0ZjBkMzc5MjZiMDg2Y2Q1YjFiNSIsInVzZXJuYW1lIjoic3ZuIiwiaWF0IjoxNjg0MDczMTI5LCJleHAiOjE2ODQxNTk1Mjl9.MLsyMrvlJbBRwnndfbLW3LNhcntHDuZd6BO3OSl6Yxs

###
POST http://localhost:3000/routes/search
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWI0ZjBkMzc5MjZiMDg2Y2Q1YjFiNSIsInVzZXJuYW1lIjoic3ZuIiwiaWF0IjoxNjg0OTA3MDM2LCJleHAiOjE2ODQ5OTM0MzZ9.IFVk7zHtXZDcQVdlOFoxxwjCP2L1GGyRF8dnqmI29Fc
Content-Type: application/json

{
  "start": "64699f8fa39bcf193c8be630",
  "end": "64699f8fa39bcf193c8be636"
}



###

GET http://localhost:3000/routes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWI0ZjBkMzc5MjZiMDg2Y2Q1YjFiNSIsInVzZXJuYW1lIjoic3ZuIiwiaWF0IjoxNjg0MTE5MDc5LCJleHAiOjE2ODQyMDU0Nzl9.wtt9OO94QECz7-XcHI40_OY5X1O50JvBEZMHPeL5_eM

###
POST http://localhost:3000/routes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWI0ZjBkMzc5MjZiMDg2Y2Q1YjFiNSIsInVzZXJuYW1lIjoic3ZuIiwiaWF0IjoxNjg0MTE5MDc5LCJleHAiOjE2ODQyMDU0Nzl9.wtt9OO94QECz7-XcHI40_OY5X1O50JvBEZMHPeL5_eM
Content-Type: application/json

{
  "_id": "64608f9f128f9cff72504100",
  "price": 7000,
  "start": "64607f81128f9cff725040fd",
  "end": "64608317128f9cff725040fe",
  "timeline": [
    "12:05",
    "12:10",
    "12:20",
    "12:30"
  ],
  "places": [
    "Stop 1",
    "Stop 2",
    "Stop 3",
    "Stop 4"
  ]
}

###
DELETE http://localhost:3000/logout/
