POST http://localhost:3000/login/
Content-Type: application/json

{
    "username": "user"
}


###

GET http://localhost:3000/routes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ1c2VyIiwiaWF0IjoxNjgzNTMyMDkyLCJleHAiOjE2ODM2MTg0OTJ9.Bo1ziSFTW3RNMnGCUFU3l5szAziFYntf_C8Eux30biU
###

POST http://localhost:3000/token/
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ1c2VyIiwiaWF0IjoxNjgzNTMyMDkyLCJleHAiOjE2ODQxMzY4OTJ9.p114aQGfSbwYvqRbUO6BY0ymtejVuLDBgn8DyITI0Wo"
}

###
DELETE http://localhost:3000/logout/
